"""initial_schema

Revision ID: 90d922c029c3
Revises:
Create Date: 2026-07-03 07:41:19.216752

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90d922c029c3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("video_id", sa.String(length=64), nullable=True),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column("uploader", sa.Text(), nullable=True),
        sa.Column("uploader_id", sa.Text(), nullable=True),
        sa.Column("channel", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("upload_date", sa.String(length=16), nullable=True),
        sa.Column("chapter_count", sa.Integer(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("output_title", sa.Text(), nullable=True),
        sa.Column("destination_folder", sa.Text(), nullable=True),
        sa.Column("final_output_path", sa.Text(), nullable=True),
        sa.Column("output_file_size", sa.Integer(), nullable=True),
        sa.Column("collision_mode", sa.String(length=20), nullable=False),
        sa.Column("embed_metadata", sa.Boolean(), nullable=False),
        sa.Column("embed_thumbnail", sa.Boolean(), nullable=False),
        sa.Column("embed_chapters", sa.Boolean(), nullable=False),
        sa.Column("trigger_abs_scan", sa.Boolean(), nullable=False),
        sa.Column("allow_reimport", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "downloading",
                "postprocessing",
                "converting",
                "verifying",
                "scanning",
                "succeeded",
                "failed",
                "cancelled",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("phase", sa.String(length=32), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("progress_eta", sa.String(length=32), nullable=True),
        sa.Column("progress_speed", sa.String(length=32), nullable=True),
        sa.Column("progress_label", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("work_dir", sa.Text(), nullable=True),
        sa.Column("log_file_path", sa.Text(), nullable=True),
        sa.Column("rq_job_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "imported_videos",
        sa.Column("video_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_title", sa.Text(), nullable=True),
        sa.Column(
            "imported_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("rq_job_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_metadata", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_attempts")
    op.drop_table("imported_videos")
    op.drop_table("jobs")
    # ### end Alembic commands ###
